//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalizationExample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalizationExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Name.
        /// </summary>
        public static string MainWindow_BookName {
            get {
                return ResourceManager.GetString("MainWindow_BookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Rating.
        /// </summary>
        public static string MainWindow_BookRating {
            get {
                return ResourceManager.GetString("MainWindow_BookRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string MainWindow_ChangeButtonText {
            get {
                return ResourceManager.GetString("MainWindow_ChangeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Languages.
        /// </summary>
        public static string MainWindow_Label_SupportedLanguages {
            get {
                return ResourceManager.GetString("MainWindow_Label_SupportedLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string MainWindow_Price {
            get {
                return ResourceManager.GetString("MainWindow_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Date.
        /// </summary>
        public static string MainWindow_PublishingDate {
            get {
                return ResourceManager.GetString("MainWindow_PublishingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Culture.
        /// </summary>
        public static string MainWindow_Ribbon_ChangeCultureTab_Title {
            get {
                return ResourceManager.GetString("MainWindow_Ribbon_ChangeCultureTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MainWindow_Ribbon_HelpTab_About_ButtonText {
            get {
                return ResourceManager.GetString("MainWindow_Ribbon_HelpTab_About_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalization / Localization example application..
        /// </summary>
        public static string MainWindow_Ribbon_HelpTab_About_Message {
            get {
                return ResourceManager.GetString("MainWindow_Ribbon_HelpTab_About_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainWindow_Ribbon_HelpTab_Title {
            get {
                return ResourceManager.GetString("MainWindow_Ribbon_HelpTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Example.
        /// </summary>
        public static string MainWindow_WindowTitle {
            get {
                return ResourceManager.GetString("MainWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average book.
        /// </summary>
        public static string Rating_AverageBook {
            get {
                return ResourceManager.GetString("Rating_AverageBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below average book.
        /// </summary>
        public static string Rating_BelowAverageBook {
            get {
                return ResourceManager.GetString("Rating_BelowAverageBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent book.
        /// </summary>
        public static string Rating_ExcellentBook {
            get {
                return ResourceManager.GetString("Rating_ExcellentBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book is good.
        /// </summary>
        public static string Rating_GoodBook {
            get {
                return ResourceManager.GetString("Rating_GoodBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not that good.
        /// </summary>
        public static string Rating_PoorBook {
            get {
                return ResourceManager.GetString("Rating_PoorBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not worth reading.
        /// </summary>
        public static string Rating_UselessBook {
            get {
                return ResourceManager.GetString("Rating_UselessBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very good book.
        /// </summary>
        public static string Rating_VeryGoodBook {
            get {
                return ResourceManager.GetString("Rating_VeryGoodBook", resourceCulture);
            }
        }
    }
}
